name: FastAPI y Docker

on:
    push: 
        branches: main
    
    workflow_dispatch: 

jobs:
    build-push-docker-image: 
        name: Build and push docker image to Docker Hub
        runs-on: ubuntu-latest
        
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME  }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: braulioll/estudiantes_api:latest